In [1]:
#NAME :LAVANYA.B
#REGISTER NO:21UAI049

In [3]:
#11.
def pypart(n):
    myList = []
    for i in range(1,n+1):
        myList.append("*"*i)
    print("\n".join(myList))
n = 7
pypart(n)

*
**
***
****
*****
******
*******


In [2]:
#12.
def remove_chars(word, n):
    print('Original string:', word)
    x = word[n:]
    return x

print("Removing characters from a string")
print(remove_chars("Lavanya", 4))
print(remove_chars("Lavanya", 2))

Removing characters from a string
Original string: Lavanya
nya
Original string: Lavanya
vanya


In [ ]:
#13.
for i in range(5): 
    n = int(input("Enter a number: ")) 
 
    if n % 5 == 0: 
        print(n) 

In [2]:
#14.
words = ["hi", "hi", "hi", "welcome"]
n_hi = words.count("hi")
print(n_hi)

3


In [4]:
#15.
num = 10
for n in range(1, num):
    for i in range(1, n+1):
        print(i, end=" ")
    print("")

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 
1 2 3 4 5 6 7 
1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 9 


In [7]:
#16.
number = int(input("Please Enter any Value: "))
reverse = 0
temp = number
while(temp > 0):
    Reminder = temp % 10
    reverse = (reverse * 10) + Reminder
    temp = temp //10
     print("Reverse of it is = %d" %reverse)
if(number == reverse):
    print("%d is a Palindrome" %number)
else:
    print("%d is Not" %number)

Please Enter any Value: 545
Reverse of it is = 545
545 is a Palindrome


In [9]:
#17.string
myList = [25,34,67,87,90,43]
print("Initial List : ", myList)
length = len(myList)
temp = myList[0]
myList[0] = myList[length - 1]
myList[length - 1] = temp

print("List after Swapping : ", myList)

Initial List :  [25, 34, 67, 87, 90, 43]
List after Swapping :  [43, 34, 67, 87, 90, 25]


In [16]:
#18.
def swapPositions(list, pos1, pos2):
     
    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list
 
List = [23, 65, 19, 90]
pos1, pos2  = 1, 3
 
print(swapPositions(List, pos1-1, pos2-1))

[19, 65, 23, 90]


In [19]:
#19.
test_list = [ 56,23,76,89,12 ]
print ("The list is : " + str(test_list))
counter = 0
for i in test_list:
    counter = counter + 1
print ("Length of list using naive method is : " + str(counter))

The list is : [56, 23, 76, 89, 12]
Length of list using naive method is : 5


In [21]:
#20.
def maximum(a, b):
      
    if a >= b:
        return a
    else:
        return b
a = 25
b = 14
print(maximum(a, b))

25


In [24]:
#21.
def minimum(a, b):
      
    if a <= b:
        return a
    else:
        return b
a = 25
b = 14
print(minimum(a, b))

14


In [33]:
#22.
string = 'amaama'
half = int(len(string) / 2)
 
if len(string) % 2 == 0:  # even
    first_str = string[:half]
    second_str = string[half:]
else:  # odd
    first_str = string[:half]
    second_str = string[half+1:]
if first_str == second_str:
    print(string, 'string is symmertical')
else:
    print(string, 'string is not symmertical')
if first_str == second_str[::-1]: 
    print(string, 'string is palindrome')
else:
    print(string, 'string is not palindrome')


amaama string is symmertical
amaama string is palindrome


In [35]:
#23.
string = "Hi this is Lavanya"
s = string.split()[::-1]
l = []
for i in s:
   
    l.append(i)

print(" ".join(l))

Lavanya is this Hi


In [37]:
#24.
test_str = "Lavanya" 
print ("The original string is : " + test_str)
new_str = ""
  
for i in range(len(test_str)):
    if i != 2:
        new_str = new_str + test_str[i] 
print ("The string after removal of i'th character : " + new_str)

The original string is : Lavanya
The string after removal of i'th character : Laanya


In [39]:
#25.tuples
import sys
Tuple1 = ("A", 1, "B", 2, "C", 3)
Tuple2 = ("Sasi", "Kalai", "Hari", "Lavanya", "deeva", "Deepanshu")
Tuple3 = ((1, "Lion"), ( 2, "Tiger"), (3, "Fox"), (4, "Wolf"))
print("Size of Tuple1: " + str(sys.getsizeof(Tuple1)) + "bytes")
print("Size of Tuple2: " + str(sys.getsizeof(Tuple2)) + "bytes")
print("Size of Tuple3: " + str(sys.getsizeof(Tuple3)) + "bytes")

Size of Tuple1: 88bytes
Size of Tuple2: 88bytes
Size of Tuple3: 72bytes


In [40]:
#26.
test_tup = (5, 20, 3, 7, 6, 8)
print("The original tuple is : " + str(test_tup))
K = 2
res = []
test_tup = list(sorted(test_tup))
 
for idx, val in enumerate(test_tup):
    if idx < K or idx >= len(test_tup) - K:
        res.append(val)
res = tuple(res)
print("The extracted values : " + str(res))

The original tuple is : (5, 20, 3, 7, 6, 8)
The extracted values : (3, 5, 8, 20)


In [42]:
#27.
test_tup = (34,56,87,97,23)
print("The original tuple is : " + str(test_tup)) 
res = sum(list(test_tup))
print("The summation of tuple elements are : " + str(res)) 

The original tuple is : (34, 56, 87, 97, 23)
The summation of tuple elements are : 297


In [44]:
#28.DICTIONARY
def dictionairy():
    key_value = {}
    key_value[2] = 25
    key_value[1] = 10
    key_value[5] = 1
    key_value[4] = 24
    key_value[6] = 18
    key_value[3] = 3237
 
    print("Task 1:-\n")
 
    print("key_value", key_value)

    for i in sorted(key_value.keys()):
        print(i, end=" ")
 
 
def main():
    
    dictionairy()
if __name__ == "__main__":
    main()

Task 1:-

key_value {2: 25, 1: 10, 5: 1, 4: 24, 6: 18, 3: 3237}
1 2 3 4 5 6 

In [46]:
#33
import random as rn
dict = {}
x, y, z = 20,45,67
dict[x, y, z] = x + y - z;
x, y, z = 5, 2, 4
dict[x, y, z] = x + y - z;
print(dict)

{(20, 45, 67): -2, (5, 2, 4): 3}


In [48]:
#34
def returnSum(myDict):
 
    list = []
    for i in myDict:
        list.append(myDict[i])
    final = sum(list)
 
    return final
dict = {'a': 100, 'b': 900, 'c': 800}
print("Sum :", returnSum(dict))

Sum : 1800


In [52]:
#35 SET
import sys
Set1 = {"A", 1, "B", 2, "C", 3}
Set2 = {"Gopal", "Raju", "Lavanya", "Nikhil", "Lucky", "Deepanshu"}
Set3 = {(1, "Lion"), ( 2, "Tiger"), (3, "Fox")}

print("Size of Set1: " + str(sys.getsizeof(Set1)) + "bytes")
print("Size of Set2: " + str(sys.getsizeof(Set2)) + "bytes")
print("Size of Set3: " + str(sys.getsizeof(Set3)) + "bytes")

Size of Set1: 472bytes
Size of Set2: 472bytes
Size of Set3: 216bytes


In [53]:
#36
test_set = set("Lavanya")

for val in test_set:
    print(val)

n
v
L
a
y


In [55]:
#37
gfg_list=[23,45,67,89,23]
min_ele,max_ele=gfg_list[0],gfg_list[0] 
for i in range(1,len(gfg_list)):
    if gfg_list[i]<min_ele:
        min_ele=gfg_list[i]
    if gfg_list[i]>max_ele:
        max_ele=gfg_list[i]
print('Minimum Element in the list',gfg_list,'is',min_ele)
print('Maximum Element in the list',gfg_list,'is',max_ele)

Minimum Element in the list [23, 45, 67, 89, 23] is 23
Maximum Element in the list [23, 45, 67, 89, 23] is 89


In [57]:
#38 MATRIX
test_list = [[23,45,67], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
print("The original list : " + str(test_list))
res = {test_list[0][ele] :  test_list[ele + 1] for ele in range(len(test_list) - 1)}
print("The Assigned Matrix : " + str(res))

The original list : [[23, 45, 67], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned Matrix : {23: [2, 0, 9], 45: [5, 4, 2], 67: [2, 3, 9]}


In [59]:
#39 
import numpy as np
A = np.array([[14, 25], [73, 4]])
  
B = np.array([[48, 58], [69, 79]])
  
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
  
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[14 25]
 [73  4]]
Printing elements of second matrix
[[48 58]
 [69 79]]
Addition of two matrix
[[ 62  83]
 [142  83]]


In [61]:
#40
from itertools import groupby
test_list = [12,34,56,78,92]
print("The original list : " + str(test_list))
res = [list(val) for key, val in groupby(sorted(test_list))]  
print("Matrix after grouping : " + str(res))

The original list : [12, 34, 56, 78, 92]
Matrix after grouping : [[12], [34], [56], [78], [92]]


In [62]:
#41FUNCTIONS 
import inspect
import collections
print(inspect.signature(collections.Counter))

(iterable=None, /, **kwds)


In [63]:
#42
def GFG(name, num):
    print("Hello from ", name + ', ' + num)
  
  
GFG("Lavanya", "25")

Hello from  Lavanya, 25


In [64]:
#43
def power(N, P):
 
    if P == 0:  
        return 1
   
    return (N*power(N, P-1)) 
N = 5
P = 0
 
print(power(N, P))

1
